In [38]:
import numpy as np

In [39]:
def get_random_angle(hi):
    # Return a random angle in the interval [0, hi)
    return np.random.random() * hi

In [40]:
# Define coefficients of Sin(beta) polynomial
def zeta_f(mc, mb):
    return 1.0-mc/mb
def xi_f(alpha):
    return 2.0/np.tan(alpha)
def chi_f(alpha, mc, ma):
    return 1.0/(np.tan(alpha)**2) - (mc/ma)/(np.sin(alpha)**2) - 1.0

In [41]:
def get_beta(alpha, mc, mb, ma):
    # Form root coefficients
    zeta = zeta_f(mc, mb)
    xi = xi_f(alpha)
    chi = chi_f(alpha, mc, ma)
    a = chi + zeta
    c = 1
    # plus and minus (p/m) for different square root signs
    print('det: {}'.format(xi**2 - 4*zeta*a))
    dp = (xi + np.sqrt(xi**2 - 4 * zeta * a))/(2 * a)
    dm = (xi - np.sqrt(xi**2 - 4 * zeta * a))/(2 * a)
    bp = zeta/dp
    bm = zeta/dm
    # Now the 8 roots
    s1 = dp/np.sqrt(c**2 + dp**2)
    s2 = -s1
    s3 = dm/np.sqrt(c**2 + dm**2)
    s4 = -s3
    s5 = bp/np.sqrt(a**2 + bp**2)
    s6 = -s5
    s7 = bm/np.sqrt(a**2 + bm**2)
    s8 = -s7
    sval = np.array([s1, s2, s3, s4, s5, s6, s7, s8])
    # And finally take the inverse sine
    beta = np.arcsin(sval)
    return beta

In [42]:
def get_unit_vectors(vec):
    # Calculate and return the following unit vectors:
    # 1 Parallel
    # 2 Perpendicular
    x_hat = np.array([1.0, 0.0, 0.0])
    y_hat = np.array([0.0, 1.0, 0.0])
    z_hat = np.array([0.0, 0.0, 1.0])
    zeros = np.array([0.0, 0.0, 0.0])
    u_par = vec/np.linalg.norm(vec)
    print(vec)
    print(u_par)
    print(x_hat)
    u_perp_1 = np.cross(u_par, x_hat)
    if np.array_equal(u_perp_1, zeros):
        u_perp_1 = np.cross(u_par, y_hat)
    u_perp_2 = np.cross(u_par, u_perp_1)
    return u_par, u_perp_1, u_perp_2

In [43]:
def get_pa_pb(alpha, phi, pc, mc, mb, ma):
    beta_val = get_beta(alpha, mc, mb, ma)
    beta = np.random.choice(beta_val)
    pc_par, pc_perp_1, pc_perp_2 = get_unit_vectors(pc)
    vhat = np.cos(phi) * pc_perp_1 + np.sin(phi) * pc_perp_2
    pa_hat = np.cos(alpha) * pc_par + np.sin(alpha) * vhat
    pb_hat = np.cos(beta) * pc_par - np.sin(beta) * vhat
    pb_mag = np.linalg.norm(pc)/(np.sin(beta)/np.tan(alpha) + np.cos(beta))
    pb = pb_hat * pb_mag
    pa_mag = pb_mag * np.sin(beta)/np.sin(alpha)
    pa = pa_hat * pa_mag
    return pa, pb

In [44]:
def get_va_vb(pc, mc, mb, ma):
    alpha = get_random_angle(np.pi)
    phi = get_random_angle(2*np.pi)
    pa, pb = get_pa_pb(alpha, phi, pc, mc, mb, ma)
    va = pa/ma
    vb = pb/mb
    return va, vb

In [45]:
get_va_vb([1.0, 1.0, 1.0], 3.0, 2.0, 1.0)

det: -9.0
[1.0, 1.0, 1.0]
[ 0.57735027  0.57735027  0.57735027]
[ 1.  0.  0.]


/home/eugene/anaconda23/envs/py3/lib/python3.5/site-packages/ipykernel/__main__.py:10: RuntimeWarning: invalid value encountered in sqrt
/home/eugene/anaconda23/envs/py3/lib/python3.5/site-packages/ipykernel/__main__.py:11: RuntimeWarning: invalid value encountered in sqrt


(array([ nan,  nan,  nan]), array([ nan,  nan,  nan]))